server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: order-service

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka # eureka服务端地址信息

# 针对user-service服务指定负载均衡规则
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 配置负载均衡懒加载
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: user-service # 是集合，如果只有一份可以直接写！
      #- user-service # 指定饥饿加载的服务名称，就是指定要拉取的服务列表
